# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_drink_builder.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 274)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_drink_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_drink_name.setObjectName("lineEdit_drink_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_drink_name)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_abv = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_abv.setObjectName("label_abv")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_abv)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_acid = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_acid.setObjectName("label_acid")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_acid)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_sugar = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_sugar.setObjectName("label_sugar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_sugar)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 100, 92, 57))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_shaken = QtWidgets.QRadioButton(self.widget)
        self.radioButton_shaken.setObjectName("radioButton_shaken")
        self.gridLayout.addWidget(self.radioButton_shaken, 0, 0, 1, 1)
        self.radioButton_stirred = QtWidgets.QRadioButton(self.widget)
        self.radioButton_stirred.setObjectName("radioButton_stirred")
        self.gridLayout.addWidget(self.radioButton_stirred, 1, 0, 1, 1)
        self.tableWidget_drink_ing = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_drink_ing.setGeometry(QtCore.QRect(210, 10, 581, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_drink_ing.sizePolicy().hasHeightForWidth())
        self.tableWidget_drink_ing.setSizePolicy(sizePolicy)
        self.tableWidget_drink_ing.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.tableWidget_drink_ing.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_drink_ing.setAlternatingRowColors(True)
        self.tableWidget_drink_ing.setRowCount(0)
        self.tableWidget_drink_ing.setColumnCount(4)
        self.tableWidget_drink_ing.setObjectName("tableWidget_drink_ing")
        self.tableWidget_drink_ing.horizontalHeader().setVisible(True)
        self.tableWidget_drink_ing.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_drink_ing.horizontalHeader().setHighlightSections(False)
        self.tableWidget_drink_ing.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_drink_ing.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_drink_ing.verticalHeader().setVisible(False)
        self.tableWidget_drink_ing.verticalHeader().setSortIndicatorShown(False)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Drink Name:"))
        self.label.setText(_translate("Dialog", "ABV (%)"))
        self.label_abv.setText(_translate("Dialog", "<value>"))
        self.label_2.setText(_translate("Dialog", "Acid (%)"))
        self.label_acid.setText(_translate("Dialog", "<value>"))
        self.label_3.setText(_translate("Dialog", "Sugar (%)"))
        self.label_sugar.setText(_translate("Dialog", "<value>"))
        self.radioButton_shaken.setText(_translate("Dialog", "Shaken"))
        self.radioButton_stirred.setText(_translate("Dialog", "Stirred"))
        self.tableWidget_drink_ing.setSortingEnabled(True)

