# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_recipes = QtWidgets.QWidget()
        self.tab_recipes.setObjectName("tab_recipes")
        self.layoutWidget = QtWidgets.QWidget(self.tab_recipes)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 652, 194))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_drinks = QtWidgets.QListWidget(self.layoutWidget)
        self.list_drinks.setObjectName("list_drinks")
        self.horizontalLayout.addWidget(self.list_drinks)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.formLayout_5 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_drink_name = QtWidgets.QLabel(self.widget)
        self.label_drink_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_drink_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drink_name.setObjectName("label_drink_name")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_drink_name)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_drink_abv = QtWidgets.QLabel(self.widget)
        self.label_drink_abv.setObjectName("label_drink_abv")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_drink_abv)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_drink_sugar = QtWidgets.QLabel(self.widget)
        self.label_drink_sugar.setObjectName("label_drink_sugar")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_drink_sugar)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_drink_acid = QtWidgets.QLabel(self.widget)
        self.label_drink_acid.setObjectName("label_drink_acid")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_drink_acid)
        self.horizontalLayout.addWidget(self.widget)
        self.list_liquids = QtWidgets.QListWidget(self.layoutWidget)
        self.list_liquids.setObjectName("list_liquids")
        self.horizontalLayout.addWidget(self.list_liquids)
        self.pushButton_add_drink = QtWidgets.QPushButton(self.tab_recipes)
        self.pushButton_add_drink.setGeometry(QtCore.QRect(202, 210, 81, 32))
        self.pushButton_add_drink.setObjectName("pushButton_add_drink")
        self.pushButton_edit_drink = QtWidgets.QPushButton(self.tab_recipes)
        self.pushButton_edit_drink.setGeometry(QtCore.QRect(130, 210, 81, 32))
        self.pushButton_edit_drink.setObjectName("pushButton_edit_drink")
        self.tabWidget.addTab(self.tab_recipes, "")
        self.tab_ing = QtWidgets.QWidget()
        self.tab_ing.setObjectName("tab_ing")
        self.list_ingredients = QtWidgets.QListWidget(self.tab_ing)
        self.list_ingredients.setGeometry(QtCore.QRect(20, 10, 256, 171))
        self.list_ingredients.setObjectName("list_ingredients")
        self.pushButton_ing_add = QtWidgets.QPushButton(self.tab_ing)
        self.pushButton_ing_add.setGeometry(QtCore.QRect(182, 180, 101, 32))
        self.pushButton_ing_add.setObjectName("pushButton_ing_add")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_ing)
        self.formLayoutWidget.setGeometry(QtCore.QRect(290, 10, 231, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_ing_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ing_name.setObjectName("lineEdit_ing_name")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ing_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_ing_abv = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ing_abv.sizePolicy().hasHeightForWidth())
        self.lineEdit_ing_abv.setSizePolicy(sizePolicy)
        self.lineEdit_ing_abv.setObjectName("lineEdit_ing_abv")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ing_abv)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_ing_acid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ing_acid.setObjectName("lineEdit_ing_acid")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ing_acid)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_ing_sugar = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ing_sugar.setObjectName("lineEdit_ing_sugar")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ing_sugar)
        self.pushButton_ing_save = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ing_save.sizePolicy().hasHeightForWidth())
        self.pushButton_ing_save.setSizePolicy(sizePolicy)
        self.pushButton_ing_save.setObjectName("pushButton_ing_save")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_ing_save)
        self.pushButton_ing_del = QtWidgets.QPushButton(self.tab_ing)
        self.pushButton_ing_del.setGeometry(QtCore.QRect(120, 180, 71, 32))
        self.pushButton_ing_del.setObjectName("pushButton_ing_del")
        self.tabWidget.addTab(self.tab_ing, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_drink_name.setText(_translate("MainWindow", "Drink Name"))
        self.label_3.setText(_translate("MainWindow", "ABV"))
        self.label_drink_abv.setText(_translate("MainWindow", "<name>"))
        self.label_6.setText(_translate("MainWindow", "Sugar"))
        self.label_drink_sugar.setText(_translate("MainWindow", "<name>"))
        self.label_8.setText(_translate("MainWindow", "Acid"))
        self.label_drink_acid.setText(_translate("MainWindow", "<name>"))
        self.pushButton_add_drink.setText(_translate("MainWindow", "Add Drink"))
        self.pushButton_edit_drink.setText(_translate("MainWindow", "Edit Drink"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_recipes), _translate("MainWindow", "Recipes"))
        self.pushButton_ing_add.setText(_translate("MainWindow", "+ Add New"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "ABV (%)"))
        self.label_12.setText(_translate("MainWindow", "Acid (%)"))
        self.label_13.setText(_translate("MainWindow", "Sugar (%)"))
        self.pushButton_ing_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_ing_del.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ing), _translate("MainWindow", "Ingredients"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Drink Builder"))

